CREATE TABLE `assessment_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`childName` varchar(255) NOT NULL,
	`idNumber` varchar(20),
	`gender` enum('M','F'),
	`birthDate` varchar(20) NOT NULL,
	`testDate` varchar(20) NOT NULL,
	`ageInMonths` int NOT NULL,
	`ageGroup` varchar(50) NOT NULL,
	`careQuestion1` enum('yes','no'),
	`careQuestion1Description` text,
	`careQuestion2` enum('yes','no'),
	`careQuestion2Description` text,
	`careQuestion3` enum('yes','no'),
	`careQuestion3Description` text,
	`grossMotorScores` json,
	`fineMotorScores` json,
	`cognitiveLanguageScores` json,
	`socialDevelopmentScores` json,
	`grossMotorTotal` int,
	`fineMotorTotal` int,
	`cognitiveLanguageTotal` int,
	`socialDevelopmentTotal` int,
	`grossMotorStatus` enum('pass','fail'),
	`fineMotorStatus` enum('pass','fail'),
	`cognitiveLanguageStatus` enum('pass','fail'),
	`socialDevelopmentStatus` enum('pass','fail'),
	`recommendation` text,
	`pdfFileKey` varchar(255),
	`pdfFileUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `assessment_records_id` PRIMARY KEY(`id`)
);
